M48
; DRILL file {KiCad (6.99.0-3325-gcb6b2da55f)} date Tue May  2 13:50:08 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-02T13:50:08+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.99.0-3325-gcb6b2da55f)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1575
%
G90
G05
T1
X4.148Y-3.964
X4.15Y-5.066
X5.842Y-3.964
X5.842Y-5.068
T2
X4.3807Y-5.0572
X5.0149Y-5.0565
T0
M30
